### ISSUE TITLE
Backfill not appearing in dropdown

### ISSUE THREAD

**Issue by elauser** [elauser/airflow_backfill_plugin#1]
A problem has been reported, where the plugin is installed and shows up in the plugins admin tab but the backfill icon doesn't show up.

The issue appears with the following composer instance
Composer version: 2.0.8
Airflow version: 2.2.3

The backfill window is still available by appending /admin/backfill to the URL.
I think this might be a composer configuration issue, as the specific airflow version has been tested locally.

**Comment by mhassan01** [comment]
Also, The issue appears with the following composer instance
Composer version: 2.0.9
Airflow version: 2.1.4

**Comment by huymq1710** [comment]
the backfill icon doesn't show up
Airflow version: 2.5.1

@elauser Do you have an ideal to fix this issue ?

**Comment by mhassan01** [comment]
Hi @huymq1710  , 
you need to add two airflow configuration overrides : 
web server.reload_on_plugin_change==True 
webserver.rbac user registration role==Admin

it will work with you
